#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

for E in $(cargo run --example --package kutil-cli 2>&1 | grep --extended-regexp '^    ' | sort); do
	cargo run --example "$E" --package kutil-cli --features=derive
done
